version: "3.8"

# creating a docker container for back-end with image referencing Docker Hub 
services:
  frontend:
    container_name: frontend
    #image: roblewisqa/frontend:latest
    build: ./app2/frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

  keypair-generator:
    container_name: keypair-generator
    #image: roblewisqa/keypair-generator:latest
    build: ./app2/keypair-generator
    ports:
    - target: 5001
      published: 5001
      protocol: tcp

  credentials:
    container_name: credentials
    #image: roblewisqa/credentials:latest
    build: ./app2/credentials
    ports:
    - target: 5002
      published: 5002
      protocol: tcp

  blockchain-engine:
    container_name: blockchain-engine
    #image: roblewisqa/blockchain-engine:latest
    build: ./app2/blockchain-engine
    ports:
    - target: 5003
      published: 5003
      protocol: tcp

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./app2/nginx/nginx.conf
      target: /etc/nginx/nginx.conf