apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://frontend:5000;
      }
      location / {
        proxy_pass http://keypair-generator:5001;
      }
      location / {
        proxy_pass http://credentials:5002;
      }
      location / {
        proxy_pass http://blockchain-engine:5003;
      }
    }