apiVersion: apps/v1
kind: Deployment
metadata:
  name: credentials
  labels:
    app: credentials

spec:
  selector:
    matchLabels:
      app: credentials
  replicas: 1

  template:
    metadata:
      name: credentials
      labels:
        app: credentials
    spec:
      containers:
      - name: credentials
        image: roblewisqa/credentials:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        
---
apiVersion: v1
kind: Service
metadata:
  name: credentials
spec:
  selector:
    app: credentials
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
  type: ClusterIP