apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database

spec:
  selector:
    matchLabels:
      app: database
  replicas: 1

  template:
    metadata:
      name: database
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: roblewisqa/database:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5006
        
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
  - port: 5006
    targetPort: 5006
    protocol: TCP
  type: ClusterIP