apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-login
  labels:
    app: frontend-login

spec:
  selector:
    matchLabels:
      app: frontend-login
  replicas: 1

  template:
    metadata:
      name: frontend-login
      labels:
        app: frontend-login
    spec:
      containers:
      - name: frontend-login
        image: roblewisqa/frontend_login:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5007
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-login
spec:
  selector:
    app: frontend-login
  ports:
  - port: 5007
    targetPort: 5007
    protocol: TCP
  type: ClusterIP