apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend

spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1

  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: roblewisqa/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP