apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandas-jsonreader
  labels:
    app: pandas-jsonreader

spec:
  selector:
    matchLabels:
      app: pandas-jsonreader
  replicas: 2

  template:
    metadata:
      name: pandas-jsonreader
      labels:
        app: pandas-jsonreader
    spec:
      containers:
      - name: pandas-jsonreader
        image: roblewisqa/pandas_jsonreader:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
        
---
apiVersion: v1
kind: Service
metadata:
  name: pandas-jsonreader
spec:
  selector:
    app: pandas-jsonreader
  ports:
  - port: 5005
    targetPort: 5005
    protocol: TCP
  type: ClusterIP