apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator
  labels:
    app: password-generator

spec:
  selector:
    matchLabels:
      app: password-generator
  replicas: 1

  template:
    metadata:
      name: password-generator
      labels:
        app: password-generator
    spec:
      containers:
      - name: password-generator
        image: roblewisqa/password_generator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        
---
apiVersion: v1
kind: Service
metadata:
  name: password-generator
spec:
  selector:
    app: password-generator
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
  type: ClusterIP