apiVersion: apps/v1
kind: Deployment
metadata:
  name: password_generator
  labels:
    app: password_generator

spec:
  selector:
    matchLabels:
      app: password_generator
  replicas: 2

  template:
    metadata:
      name: password_generator
      labels:
        app: password_generator
    spec:
      containers:
      - name: password_generator
        image: roblewisqa/password_generator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        
---
apiVersion: v1
kind: Service
metadata:
  name: password_generator
spec:
  selector:
    app: password_generator
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
  type: ClusterIP