apiVersion: apps/v1
kind: Deployment
metadata:
  name: seedphrase_generator
  labels:
    app: seedphrase_generator

spec:
  selector:
    matchLabels:
      app: seedphrase_generator
  replicas: 2

  template:
    metadata:
      name: seedphrase_generator
      labels:
        app: seedphrase_generator
    spec:
      containers:
      - name: seedphrase_generator
        image: roblewisqa/seedphrase_generator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: seedphrase_generator
spec:
  selector:
    app: seedphrase_generator
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP