apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordlist_parser
  labels:
    app: wordlist_parser

spec:
  selector:
    matchLabels:
      app: wordlist_parser
  replicas: 2

  template:
    metadata:
      name: wordlist_parser
      labels:
        app: wordlist_parser
    spec:
      containers:
      - name: wordlist_parser
        image: roblewisqa/wordlist_parser:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        
---
apiVersion: v1
kind: Service
metadata:
  name: wordlist_parser
spec:
  selector:
    app: wordlist_parser
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
  type: ClusterIP