version: "3.8"

# creating a docker container for back-end with image referencing Docker Hub 
services:
  Seedphrase_Generator:
    container_name: seedphrase_generator
    image: seedphrase_generator:latest
    build: ./Seedphrase_Generator
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
# creating a docker container for random_numbers with image referencing Docker Hub       
  WordList_Reader:
    container_name: wordlist_reader
    image: wordlist_reader:latest
    build: ./WordList_Reader
    ports:
    - target: 5001
      published: 5001
      protocol: tcp

  Wordlist_Parser:
    container_name: wordlist_parser
    image: wordlist_parser:latest
    build: ./WordList_Parser
    ports:
    - target: 5002
      published: 5002
      protocol: tcp

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf